// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadArranchamento(arg1, arg2) {
  return window['go']['main']['App']['DownloadArranchamento'](arg1, arg2);
}

export function DownloadWordMulti(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadWordMulti'](arg1, arg2, arg3, arg4);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function GenerateDocumentArranchamentoHTML(arg1, arg2) {
  return window['go']['main']['App']['GenerateDocumentArranchamentoHTML'](arg1, arg2);
}

export function GenerateDocumentHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDocumentHTML'](arg1, arg2, arg3);
}

export function GenerateSchedule(arg1) {
  return window['go']['main']['App']['GenerateSchedule'](arg1);
}

export function GetAllMilitares() {
  return window['go']['main']['App']['GetAllMilitares']();
}

export function GetScores(arg1) {
  return window['go']['main']['App']['GetScores'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportBackup() {
  return window['go']['main']['App']['ImportBackup']();
}

export function ImportBackupJSON(arg1) {
  return window['go']['main']['App']['ImportBackupJSON'](arg1);
}

export function InitializeState(arg1) {
  return window['go']['main']['App']['InitializeState'](arg1);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}
